
# Data generation parameters
samples:
  - sample1
  - sample2
  - sample3

# rule params
generate_data:
  n: 100

# report params
report:
  result_report_path: "simple_report/"
  resource_report_path: "resource_report/"
  



